# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: cinder-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/cinder
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/zone: nova
  name: doku-vol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  cinder:
    volumeID: e4c2aee6-4a55-4d79-9b82-8010503c4499
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
