                                                                                                                                                                                                                                                       1,1           All
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: dokuwiki
    chart: dokuwiki-6.0.13
    heritage: Tiller
    release: doku
  name: doku-pvc
  namespace: doku
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: doku-vol
